#spring文件配置
spring:
  application:
    name: frp-dashboard
  elasticsearch:
    jest:
      uris: http://114.116.110.43:9204,http://114.116.110.43:9205,http://114.116.107.3:9206,http://114.116.107.3:9207
      username: elastic
      password: Xcm2018!
      connection-timeout: 600s
      read-timeout: 1000s
  datasource:
#    url: jdbc:mysql://114.116.117.51:3306/xc_frp_test?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://192.168.101.140:3306/xc_frp?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://49.4.90.121:3306/xc_frp_test?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://49.4.90.121:3306/xc_frp_two?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    url: jdbc:mysql://49.4.90.121:3306/xc_frp_three?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://192.168.101.140:3306/xc_frp_two?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://192.168.101.140:3306/xc_frp_three?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: XcmDmp123456*@#%[{?
#    password: Caidao123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 3
#    host: 192.168.101.140
    host: 49.4.90.121
    port: 6379
    password: Xinchao123
#    password: 123456
    timeout: 60000ms
    jedis:
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

#log(使用logback)
logging:
  config: classpath:logback-spring.xml

#mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  servlet:
    context-path: /frpdashboard
  port: 8166

#终端类型
custom:
  device-type: 3
  limit-people-num: 150
