#spring文件配置
spring:
  application:
    name: frp-dashboard-three
  elasticsearch:
    jest:
      uris: http://172.16.11.38:9200,http://172.16.11.49:9200,http://172.16.11.136:9200
      username: elastic
      password: Xcm2018!
      connection-timeout: 6000s
      read-timeout: 60000s
  datasource:
    url: jdbc:mysql://172.16.10.25:3306/xc_frp_three?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: XcmDmp123456*@#%[{?
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 3
    host: 172.16.10.25
    port: 6379
    password: Xinchao123
    timeout: 6000ms
    jedis:
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 8
        min-idle: 0


#log(使用logback)
logging:
  config: classpath:logback-spring.xml

#mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  servlet:
    context-path: /frpdashboardthree
  port: 8163

#终端类型
custom:
  device-type: 3
  limit-people-num: 50